# These are supported funding model platforms

# github: rajdeepmondal

# GitHub Sponsors funding options
# Add your preferred funding platforms here

# github: rajdeepmondaldotcom
# ko_fi: rajdeepmondal
# buy_me_a_coffee: rajdeepmondal

# Remove or uncomment the above lines if you want to enable sponsorship
